version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dineflow-sql-server
    environment:
      SA_PASSWORD: "FurkanKuzucukSoftwareEngineering2026" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    

  api:
    build:
      context: . 
      dockerfile: DineFlowBackEnd/Dockerfile 
    container_name: dineflow-api
    ports:
      - "5180:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DineFlowDB;User Id=sa;Password=FurkanKuzucukSoftwareEngineering2026;TrustServerCertificate=True;"
    depends_on:
      - sqlserver 
    

  frontend:
    build:
      context: ./dineflow-frontend
      dockerfile: Dockerfile
    container_name: dineflow-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./dineflow-frontend:/app
      - /app/node_modules 
    environment:
      - VITE_API_URL=http://localhost:5180 
    depends_on:
      - api
    

volumes:
  sqlserver_data: